feat: add format targets to Makefile.ftm

diff --git a/scripts/style/Makefile.fmt b/scripts/style/Makefile.fmt
--- a/scripts/style/Makefile.fmt
+++ b/scripts/style/Makefile.fmt
@@ -18,10 +18,13 @@ CUR_DATE   := $(shell date +%Y-%m-%d_%H-%M-%S)
 
 # Directories
 GIT_DIR      := $(shell git rev-parse --show-toplevel)
+WORK_DIR     := $(CURDIR)
 SCRIPTS_DIR  := $(GIT_DIR)/scripts
 STYLE_DIR    := $(SCRIPTS_DIR)/style
+UVM_DIR      := $(GIT_DIR)/verification/uvm
+FMT_DIR      := $(WORK_DIR)/fmt_log
 RTL_DIR      := $(GIT_DIR)/rtl
-TB_DIR       :=
+TB_DIR       := $(UVM_DIR)/env $(UVM_DIR)/sv $(UVM_DIR)/tb $(UVM_DIR)/tests
 
 # Files
 RTL_FILES := $(shell find $(RTL_DIR) -name "*.sv" -or -name "*.v")
@@ -30,6 +33,7 @@ TB_FILES  := $(shell find $(TB_DIR) -name "*.sv" -or -name "*.v")
 # Verible flags
 LINT_FLAGS := --rules_config $(STYLE_DIR)/.rules.verible_lint
 FMT_FLAGS  := --flagfile=$(STYLE_DIR)/.rules.verible_format
+MODE       := check
 
 # Colors
 C_RED := \033[31m
@@ -45,16 +49,31 @@ SHELL         := bash
 
 .PHONY: all
 all: help
-#_____________________________________________________________________________)
+#______________________________________________________________________________
 
 PHONY: install-verible
 install-verible: ## Install verible
 	@$(STYLE_DIR)/install-verible.sh
 #______________________________________________________________________________
 
+.PHONY: vars
+vars: ## Print Makefile variables
+	@echo -e "$(C_ORA)Miscellaneous variables$(NC)"
+	@echo "CUR_DATE    = $(CUR_DATE)"
+	@echo -e "$(C_ORA)Directory variables$(NC)"
+	@echo "GIT_DIR     = $(GIT_DIR)"
+	@echo "WORK_DIR    = $(WORK_DIR)"
+	@echo "SCRIPTS_DIR = $(SCRIPTS_DIR)"
+	@echo "STYLE_DIR   = $(STYLE_DIR)"
+	@echo "UVM_DIR     = $(UVM_DIR)"
+	@echo "FMT_DIR     = $(FMT_DIR)"
+	@echo "RTL_DIR     = $(RTL_DIR)"
+	@echo "TB_DIR      = $(TB_DIR)"
+#______________________________________________________________________________
+
 .PHONY: list
 list: ## List all the RTL and TB files
-	@echo -e "$(C_ORA)List of RTL and TB files...$(NC)"
+	@echo -e "$(C_ORA)List of RTL and TB files$(NC)"
 	@echo -e "$(C_YEL)RTL files:$(NC)"
 	@for file in $(RTL_FILES); do \
 		echo " - $$file"; \
@@ -73,30 +92,70 @@ list: ## List all the RTL and TB files
 	fi
 #______________________________________________________________________________
 
-.PHONY: vars
-vars: ## Print Makefile variables
-	@echo -e "$(C_ORA)Miscellaneous variables$(NC)"
-	@echo "CUR_DATE    = $(CUR_DATE)"
-	@echo -e "$(C_ORA)Directory variables$(NC)"
-	@echo "GIT_DIR     = $(GIT_DIR)"
-	@echo "SCRIPTS_DIR = $(SCRIPTS_DIR)"
-	@echo "STYLE_DIR   = $(STYLE_DIR)"
-	@echo "RTL_DIR     = $(RTL_DIR)"
-	@echo "TB_DIR      = $(TB_DIR)"
-	@echo -e "$(C_ORA)Files variables$(NC)"
-	@echo "RTL_FILES   = $(RTL_FILES)"
-#______________________________________________________________________________
-
 .PHONY: lint
 lint: ## Lint the RTL and TB files (Verible)
 	@echo -e "$(C_ORA)Running Verible linting tool$(NC)"
 	@verible-verilog-lint $(LINT_FLAGS) $(RTL_FILES) $(TB_FILES) || true
 #______________________________________________________________________________
 
+.PHONY: format-rtl
+format-rtl: list ## Format RTL code [MODE: inplace|check]
+	@echo -e "$(C_ORA)Running Verible formatting tool for RTL [$(MODE) mode]$(NC)"
+	@if [ "$(MODE)" = "check" ]; then \
+		mkdir -p $(FMT_DIR)/rtl_check_$(CUR_DATE); \
+		for dir in $(RTL_DIR); do \
+			cp -r $$dir $(FMT_DIR)/rtl_check_$(CUR_DATE); \
+		done; \
+		files=$$(find $(FMT_DIR)/rtl_check_$(CUR_DATE) -name "*.sv" -or -name "*.v"); \
+	elif [ "$(MODE)" = "inplace" ]; then \
+		mkdir -p $(FMT_DIR)/rtl_backup_$(CUR_DATE); \
+		for dir in $(RTL_DIR); do \
+			cp -r $$dir $(FMT_DIR)/rtl_backup_$(CUR_DATE); \
+		done; \
+		files="$(RTL_FILES)"; \
+	else \
+		echo "Error: Invalid mode. Use MODE=inplace or MODE=check."; \
+		exit 1; \
+	fi; \
+	for file in $$files; do \
+		echo " - Formatting $$file"; \
+		verible-verilog-format $(FMT_FLAGS) $$file; \
+	done
+#______________________________________________________________________________
+
+.PHONY: format-tb
+format-tb: list ## Format TB code  [MODE: inplace|check]
+	@echo -e "$(C_ORA)Running Verible formatting tool for TB [$(MODE) mode]$(NC)"
+	@if [ "$(MODE)" = "check" ]; then \
+		mkdir -p $(FMT_DIR)/tb_check_$(CUR_DATE); \
+		for dir in $(TB_DIR); do \
+			cp -r $$dir $(FMT_DIR)/tb_check_$(CUR_DATE); \
+		done; \
+		files=$$(find $(FMT_DIR)/tb_check_$(CUR_DATE) -name "*.sv" -or -name "*.v"); \
+	elif [ "$(MODE)" = "inplace" ]; then \
+		mkdir -p $(FMT_DIR)/tb_backup_$(CUR_DATE); \
+		for dir in $(TB_DIR); do \
+			cp -r $$dir $(FMT_DIR)/tb_backup_$(CUR_DATE); \
+		done; \
+		files="$(TB_FILES)"; \
+	else \
+		echo "Error: Invalid mode. Use MODE=inplace or MODE=check."; \
+		exit 1; \
+	fi; \
+	for file in $$files; do \
+		echo " - Formatting $$file"; \
+		verible-verilog-format $(FMT_FLAGS) $$file; \
+	done
+#______________________________________________________________________________
+
+.PHONY: format
+format: format-rtl format-tb ## Format RTL and TB code
+#______________________________________________________________________________
+
 .PHONY: help
 help: ## Displays help message
 	@echo "======================================================================"
-	@echo "Usage: make <target>"
+	@echo "Usage: make <target> <variables>"
 	@echo "--------------------------- Targets ----------------------------------"
 	@grep -h -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "- make \033[36m%-15s\033[0m %s\n", $$1, $$2}'
 	@echo "======================================================================"
